# Generated by Django 3.1.3 on 2020-11-28 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=400)),
                ('valor', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('valor', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Carcasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=400)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('terminada', models.BooleanField(default=False)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
