# Generated by Django 3.1.3 on 2020-11-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carcasas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcasa',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carcasas', to='Carcasas.material'),
        ),
        migrations.AddField(
            model_name='carcasa',
            name='modeloEquipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carcasas', to='Carcasas.modeloequipo'),
        ),
    ]
