# Generated by Django 3.1.3 on 2020-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carcasas', '0002_auto_20201128_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcasa',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
