# Generated by Django 3.1.3 on 2020-11-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carcasas', '0003_auto_20201128_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcasa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
